export const fareChart = [
    {   
        "id_ride": "bike1",
        "key": "bk1",
        "type":"bike",
        "fare": 60,
        "passenger":1,
        "image": "https://i.postimg.cc/fWvZdzrP/Frame.png",
    },
    {   
        "id_ride": "bike2",
        "key": "bk1",
        "type":"bike",
        "fare": 60,
        "passenger": 1,
        "image": "https://i.postimg.cc/fWvZdzrP/Frame.png",
    },
    {   "id_ride": "bike3",
        "key": "bk1",
        "type":"bike",
        "fare": 60,
        "passenger":1,
        "image": "https://i.postimg.cc/fWvZdzrP/Frame.png",
    },
    {
        "id_ride": "car1",
        "key": "cr3",
        "type": "car",
        "fare": 85,
        "passenger":4,
        "image": "https://i.postimg.cc/wTfpWWHc/Frame-2.png",
    },
    {
        "id_ride": "car2",
        "key": "cr3",
        "type": "car",
        "fare": 85,
        "passenger": 4,
        "image": "https://i.postimg.cc/wTfpWWHc/Frame-2.png",
    },
    {
        "id_ride": "car3",
        "key": "cr3",
        "type": "car",
        "fare": 85,
        "passenger":4 ,
        "image": "https://i.postimg.cc/wTfpWWHc/Frame-2.png",
    },
    {   "id_ride": "bus1",
        "key": "bs2",
        "type": "bus",
        "fare": 93,
        "passenger":25,
        "image": "https://i.postimg.cc/vHHytRRZ/Frame-1.png",
    },
    {
        "id_ride": "bus2",
        "key": "bs2",
        "type": "bus",
        "fare": 93 ,
        "passenger": 25,
        "image": "https://i.postimg.cc/vHHytRRZ/Frame-1.png",
    },
    {
        "id_ride": "bus3",
        "key": "bs2",
        "type": "bus",
        "fare": 93 ,
        "passenger": 25,
        "image": "https://i.postimg.cc/vHHytRRZ/Frame-1.png",
    },
    {
        "id_ride": "train1",
        "key": "tn4",
        "type":"train",
        "fare": 93,
        "passenger":50,
        "image": "https://i.postimg.cc/Gm416km0/Group.png",
    },
    {
        "id_ride": "train2",
        "key": "tn4",
        "type":"train",
        "fare": 93,
        "passenger":50,
        "image": "https://i.postimg.cc/Gm416km0/Group.png",
    },
    {   
        "id_ride": "train3",
        "key": "tn4",
        "type":"train",
        "fare": 93,
        "passenger":50,
        "image": "https://i.postimg.cc/Gm416km0/Group.png",
    }
    
]